format = """
[](fg:#4C566A)\
$username\
[](fg:#4C566A bg:#8FBCBB)\
$directory\
[](fg:#8FBCBB bg:#81A1C1)\
$python\
[](fg:#81A1C1 bg:#5E81AC)\
$time\
[ ](fg:#5E81AC)\
"""

# Disable the blank line at the start of the prompt
add_newline = true

[colors]
nord3 = "#4C566A"
nord7 = "#8FBCBB"
nord9 = "#81A1C1"
nord10 = "#5E81AC"

[username]
show_always = true
style_user = "bg:#4C566A"
style_root = "bg:#4C566A"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:#8FBCBB"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[python]
style = "bg:#81A1C1"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#5E81AC"
format = '[ $time ]($style)'
